name: "Publish"

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Gradle Build and Test"
        run: ./gradlew check build publish --stacktrace
        env:
          LMCD_MAVEN: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
